zigate.tz wrong baudrate (#295)
This fix:

Error: failed to connect to zigate adapter [object Object] after 10000ms

even after the "adapter: zigate" is set in the config file. The correct baudRate for zigate is 115200